In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

## Owners

In [73]:
coowners = pd.read_csv("data/processed/pair_count_maybe_owner.csv", index_col=[0, 1])

In [90]:
def show_related(pair_df, name=None, by='pmi', limit=10):
    if not name:
        name = pd.Series(pair_df.index.levels[0]).sample(1).iloc[0]
    print(name)
    res = pair_df.loc[name].copy()
    res['ratio'] = res['count'] / res['count_y']
    res = res.sort_values(by=by, ascending=False).head(limit)
    return res

In [96]:
show_related(coowners)

Centrum Sztuki Filmowej / Kino Kosmos

,count,count_x,count_y,pmi,ratio
owner_name_y,,,,,
Centrum Sztuki Filmowej / Kino Kosmos,6373,6373,6373,4.143451,1.000000
Klub Filmowy Ambasada,27,6373,35,3.883940,0.771429
Anna Lipińska,2,6373,3,3.737986,0.666667
Inqubator Teatralny,11,6373,18,3.650975,0.611111
EMMA PAK Śląsk,6,6373,10,3.632625,0.600000
kino zakorzenione,70,6373,124,3.571665,0.564516
Uśpione opowieści - fotonarracje,66,6373,119,3.553982,0.554622
Królestwo,63,6373,116,3.532996,0.543103
Lód 9,91,6373,171,3.512647,0.532164
Strefa Centralna,11,6373,21,3.496824,0.523810

In [97]:
show_related(coowners, by='count')

Komis Płytowy Katowice

,count,count_x,count_y,pmi,ratio
owner_name_y,,,,,
Komis Płytowy Katowice,431,431,431,6.837168,1.000000
Katowice Miasto Ogrodów,218,431,28446,1.965901,0.007664
Centrum Sztuki Filmowej / Kino Kosmos,168,431,6373,3.201307,0.026361
KATO,166,431,16768,2.221929,0.009900
Festiwal Tauron Nowa Muzyka,155,431,30711,1.548217,0.005047
Kinoteatr Rialto,142,431,12917,2.326696,0.010993
Katowice Street Art Festival,127,431,7829,2.715766,0.016222
Muzeum Śląskie,125,431,11945,2.277414,0.010465
Ars Independent,115,431,7246,2.693896,0.015871
Ars Cameralis,115,431,6675,2.775976,0.017228

## Places

In [98]:
coplaces = pd.read_csv("data/processed/pair_count_maybe_place.csv", index_col=[0, 1])

In [99]:
show_related(coplaces)

Miejskie Centrum Kultury im. Henryka Bisty

,count,count_x,count_y,pmi,ratio
place_name_y,,,,,
Miejskie Centrum Kultury im. Henryka Bisty,40,40,40,9.258623,1.000000
Pub Korba,1,40,9,7.061399,0.111111
Muzeum Miejskie w Tychach,1,40,34,5.732263,0.029412
ANNA NOCON health & beauty,1,40,39,5.595062,0.025641
Śląski Inkubator Przedsiębiorczości,1,40,42,5.520954,0.023810
Dom Muzyki i Tańca w Zabrzu,1,40,53,5.288331,0.018868
Wydział Nauk Społecznych Uniwersytetu Śląskiego,1,40,72,4.981957,0.013889
Filharmonia Częstochowska,1,40,73,4.968164,0.013699
Parafia św. Józefa Katowice Załęże,2,40,148,4.954558,0.013514
Zła buka,1,40,80,4.876597,0.012500

In [100]:
show_related(coplaces, by='count')

Monopol Katowice

,count,count_x,count_y,pmi,ratio
place_name_y,,,,,
Monopol Katowice,130,130,130,8.079968,1.000000
Jazz Club Hipnoza (official venue profile),60,130,17228,2.420022,0.003483
KATO,58,130,16308,2.441000,0.003557
Muzeum Śląskie,58,130,25625,1.989088,0.002263
"Katowice, Woiwodschaft Schlesien, Polen",57,130,76568,0.877085,0.000744
Fabryka Porcelany,52,130,24408,1.928546,0.002130
Kinoteatr Rialto,49,130,13913,2.431210,0.003522
Międzynarodowe Centrum Kongresowe w Katowicach,48,130,17634,2.173585,0.002722
Śląskie. Pozytywna energia,46,130,7876,2.937034,0.005841
Kontenery Kultury,45,130,14862,2.280068,0.003028